// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deadlock} from '../models';

export function GetHeroAssets():Promise<Array<deadlock.HeroAssets>>;

export function GetMatches(arg1:string,arg2:number):Promise<Array<deadlock.PlayerMatchHistoryEntry>>;

export function SteamLogin():Promise<void>;
