// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHeroAssets() {
  return window['go']['main']['App']['GetHeroAssets']();
}

export function GetMatches(arg1, arg2) {
  return window['go']['main']['App']['GetMatches'](arg1, arg2);
}

export function SteamLogin() {
  return window['go']['main']['App']['SteamLogin']();
}
